# Generated by Django 5.2.17 on 2026-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Auto-generated composite of the color image + design, for the packing team.', null=True, upload_to='orders/previews/'),
        ),
    ]
