# Generated by Django 5.2.17 on 2026-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderitem_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
